### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-191-nikitin#7]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
5) Відомо, що з серпня 2021 року GitHub-сервер пропонує PAT 
для процесу аутентифікації під час безпечного оновлення GitHub-репозиторію. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by NikitunPVLK** [comment]
GitHub використовує токени доступу на основі PAT (Personal Access Token) для забезпечення безпечної аутентифікації та авторизації під час оновлення репозиторіїв з різних джерел.

Використання PAT замість стандартної аутентифікації через логін та пароль надає наступні переваги:

- Можна створити декілька токенів для різних цілей та репозіторіїв з різними правами доступу.

- Використання PAT дозволяє уникнути передачі свого пароля зовнішним сервісам, що підвищує безпеку облікових даних.

- Використання PAT спрощує автоматизацію процесів оновлення та управління репозиторіями. Можна створити PAT і використовувати його в скриптах, щоб безпосередньо взаємодіяти з GitHub API без введення паролів.

**Comment by oleksandrblazhko** [comment]
Оцінка = 2 бали
